### ISSUE TITLE
Documentation does not build or serve

### ISSUE THREAD

**Issue by ssilvius** [middlemac/middleman-pagegroups#1]
Following your instructions to use the extension to generate your docs (really odd to not have at least a quick summary on the github page) several pages won't build and error when served via the built-in rack server. This extension looks like it could be a good thing for the community, a real time saver. But we really can't tell.
1. error  build/documentation/index.html
2. error  build/index.html
3. error  build/documentation/nested_folder/index.html

die with `NameError: undefined local variable or method `product_uri'`

**Comment by balthisar** [comment]
@ssilvius, thanks for the report. I've fixed this in 1.0.6 / 4aa797a, as well as fixed the broken Cucumber test.

> really odd to not have at least a quick summary on the github page

I used to do that but maintaining multiple docs started to suck, but you're right, there should be something, so I've added the Yard-generated one-pager to the repo, and put a link to it in the README.

Although it's Yardoc, I went to great pains to make it work well with a Middleman extension, so it should be fairly good without having to install the demo project.
