### ISSUE TITLE
Conflicts with Middleman Localization features

### ISSUE THREAD

**Issue by bobbymarko** [middlemac/middleman-pagegroups#2]
First off, thank you for this plugin! It's been a lifesaver.

I'm trying to use pagegroups along with localized content and running into some errors. For example, if I configure l18n to not have a default locale set like so:

`activate :i18n, :mount_at_root => false`

I get this error:

`/Users/markor/.rvm/gems/ruby-2.3.3/gems/middleman-pagegroups-1.0.6/lib/middleman-pagegroups/extension.rb:423:in `block in manipulate_resource_list': undefined method `parent' for nil:NilClass (NoMethodError)
Did you mean?  present?`

Any suggestions for how I might be able to get it to work? Thanks!

**Comment by balthisar** [comment]
Can you send me a sample file that causes the error? I can't promise a fast response, but I can promise a response.

**Comment by bobbymarko** [comment]
Here's a sample repository that shows the issue: https://github.com/bobbymarko/middleman-pagegroups-localization-test

It's based off of the pagegroups documentation site. But, I added a few items to enable localization.

- Added `activate :i18n, :mount_at_root => false` to config.rb
- Root folder now has a locales folder with EN and JP sample language files. This enables localization in those two languages.
- In source there's a folder named 'localizable' where Middleman looks for files to localize by default.
- Inside of the localizable folder is a pair of index pages (one EN and one JP) and also a 'documentation' folder which contains a few of the pages of documentation but with en and jp extensions. In the files I simply wrote English or Japanese at the top to differentiate between the views.

Here's what I found: If you delete the documentation folder from within localizable the site builds just fine and you can go to localhost:4567/en and localhost:4567/jp and see the appropriate views. But as soon as you add the documentation subfolder you get the `/Users/markor/.rvm/gems/ruby-2.3.3/gems/middleman-pagegroups-1.0.6/lib/middleman-pagegroups/extension.rb:423:in 'block in manipulate_resource_list': undefined method 'parent' for nil:NilClass (NoMethodError)` error.

**Comment by balthisar** [comment]
@bobbymarko, thanks, I'll try to have a look in the next few days (sorry, overcommitted!). I accept PR's ;-)

**Comment by bobbymarko** [comment]
No worries, I totally get it! I'd love to propose a fix, but it's a little out of my comfort zone. But, I'll poke around at it and see if I can find a simple fix.

Thanks again for these plugins!

**Comment by bobbymarko** [comment]
Now I feel like a schmuck. I put two minutes into debugging it and it was a easy fix. Just sent as PR #3

**Comment by balthisar** [comment]
@bobbymarko, I'm not sure if you still use this gem, but I've just pushed a fix, which is mostly just your fix without the change to resource.parent, and your test project builds and navigates successfully.

I don't use the multilingual features, but it seems that the build folder structure of your test repo is exactly what it should be now. Essentially, there are three complete websites: /en/, /jp/, and /. This probably isn't what's intended, but I think that's what mount_as_root is doing.

If I let the english mount_as_root, then it looks like there's the /jp/ site, and /, and the contents of documentation are merged with the english-localized documentation. I'm not sure what the defined behavior is, but that seems to make sense.

In any case, I'll close this. If you're still interested in a solution or I'm not understanding how localization is supposed to work, feel free to answer back here and I'll re-open it.

**Comment by bobbymarko** [comment]
I'm still using the gem. With my fix there were some edge cases in deeper nested page groups where the menu helpers wouldn't render links for localized content. I ended up figuring out some ways to work around it, but I never found a solution for the root of the problem. It's been so long since I was dealing with it that I don't remember all of the details though. But my change you've incorporated at least makes it work a little better. Thanks for these plugins, they've been a huge help for us!
